### ISSUE TITLE
Use NUnit for testing

### ISSUE THREAD

**Issue by nickntg** [Codeh4ck/Maze-Solver#2]
In order to break the dependency on high-end versions of Visual Studio for testing, you can use NUnit as the testing framework.

**Comment by Codeh4ck** [comment]
Ignore the commit, it's an error quoting the wrong issue. It will be written using NUnit for unit tests, thanks. I will study NUnit's documentation to see how it must be implemented and upload a new version

**Comment by Codeh4ck** [comment]
Thank you for the pull request containing the fixes. I appreciate it! @nickntg

**Comment by nickntg** [comment]
My pleasure. I guess not all changes were for the best (I wasn't particularly happy with the way some of the refactoring looked after it was done) but the purpose was mostly to start incorporating real unit testing and using NUnit.

I believe that adding and using a dependency injection framework could potentially be a logical next step/enhancement but not in the context of this issue.
